spring.application.name=rest-api-cashcard

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


# H2 Console Configuration
spring.h2.console.enabled=true

# Additional Configuration
server.error.include-message=always
server.error.include-binding-errors=always
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false