# App Configuration
app.security.admin.username=test
app.security.admin.password=abc123
app.security.admin.role=ADMIN

app.security.visitor.username=visitor
app.security.visitor.password=visitor123
app.security.visitor.role=VISITOR
