# App Configuration
app.security.admin.role=ADMIN
app.security.user.role=USER

app.security.admin.username=admin
app.security.admin.password=admin123

app.security.user1.username=user1
app.security.user1.password=user@1

app.security.user2.username=user2
app.security.user2.password=user@22

